### ISSUE TITLE
KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."

### ISSUE THREAD

**Issue by DrPlanecraft** [emasterclassacademy/Single-Multiple-Custom-Object-Detection-and-Tracking#1]
Hello, when I ran your code from convert.py, everything worked fine, but once I got to object tracker, it gave me this error, im using later versions of what you used but there is no deprecation warning or anything of that nature.

full output:
C:\AI4Y\Single-Multiple-Custom-Object-Detection-and-Tracking-master\deep_sort>cd C:\AI4Y\Single-Multiple-Custom-Object-Detection-and-Tracking-master

C:\AI4Y\Single-Multiple-Custom-Object-Detection-and-Tracking-master>python Convert.py
2020-10-29 08:49:46.331770: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-29 08:49:48.421522: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-10-29 08:49:48.460141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2060 SUPER computeCapability: 7.5
coreClock: 1.68GHz coreCount: 34 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-10-29 08:49:48.460242: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-29 08:49:48.464459: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-10-29 08:49:48.466417: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-10-29 08:49:48.467077: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-10-29 08:49:48.469816: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-10-29 08:49:48.471863: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-10-29 08:49:48.478198: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-10-29 08:49:48.478344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-10-29 08:49:48.546508: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-29 08:49:48.552748: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2961cdc1050 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-29 08:49:48.552906: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-29 08:49:48.553293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2060 SUPER computeCapability: 7.5
coreClock: 1.68GHz coreCount: 34 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-10-29 08:49:48.553432: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-29 08:49:48.553643: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-10-29 08:49:48.553874: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-10-29 08:49:48.554363: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-10-29 08:49:48.554566: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-10-29 08:49:48.554771: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-10-29 08:49:48.554973: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-10-29 08:49:48.555205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-10-29 08:49:49.009932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-29 08:49:49.010073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0
2020-10-29 08:49:49.010477: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N
2020-10-29 08:49:49.010845: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6642 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-10-29 08:49:49.013136: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2964a03f880 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-29 08:49:49.013201: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2060 SUPER, Compute Capability 7.5
Model: "yolov3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input (InputLayer)              [(None, None, None,  0
__________________________________________________________________________________________________
yolo_darknet (Functional)       ((None, None, None,  40620640    input[0][0]
__________________________________________________________________________________________________
yolo_conv_0 (Functional)        (None, None, None, 5 11024384    yolo_darknet[0][2]
__________________________________________________________________________________________________
yolo_conv_1 (Functional)        (None, None, None, 2 2957312     yolo_conv_0[0][0]
                                                                 yolo_darknet[0][1]
__________________________________________________________________________________________________
yolo_conv_2 (Functional)        (None, None, None, 1 741376      yolo_conv_1[0][0]
                                                                 yolo_darknet[0][0]
__________________________________________________________________________________________________
yolo_output_0 (Functional)      (None, None, None, 3 4984063     yolo_conv_0[0][0]
__________________________________________________________________________________________________
yolo_output_1 (Functional)      (None, None, None, 3 1312511     yolo_conv_1[0][0]
__________________________________________________________________________________________________
yolo_output_2 (Functional)      (None, None, None, 3 361471      yolo_conv_2[0][0]
__________________________________________________________________________________________________
yolo_boxes_0 (Lambda)           ((None, None, None,  0           yolo_output_0[0][0]
__________________________________________________________________________________________________
yolo_boxes_1 (Lambda)           ((None, None, None,  0           yolo_output_1[0][0]
__________________________________________________________________________________________________
yolo_boxes_2 (Lambda)           ((None, None, None,  0           yolo_output_2[0][0]
__________________________________________________________________________________________________
yolo_nms (Lambda)               ((None, 100, 4), (No 0           yolo_boxes_0[0][0]
                                                                 yolo_boxes_0[0][1]
                                                                 yolo_boxes_0[0][2]
                                                                 yolo_boxes_1[0][0]
                                                                 yolo_boxes_1[0][1]
                                                                 yolo_boxes_1[0][2]
                                                                 yolo_boxes_2[0][0]
                                                                 yolo_boxes_2[0][1]
                                                                 yolo_boxes_2[0][2]
==================================================================================================
Total params: 62,001,757
Trainable params: 61,949,149
Non-trainable params: 52,608
__________________________________________________________________________________________________
I1029 08:49:50.575503  1544 Convert.py:19] model created
I1029 08:49:50.576501  1544 utils.py:46] yolo_darknet/conv2d bn
I1029 08:49:50.577498  1544 utils.py:46] yolo_darknet/conv2d_1 bn
I1029 08:49:50.579493  1544 utils.py:46] yolo_darknet/conv2d_2 bn
I1029 08:49:50.580490  1544 utils.py:46] yolo_darknet/conv2d_3 bn
I1029 08:49:50.581487  1544 utils.py:46] yolo_darknet/conv2d_4 bn
I1029 08:49:50.582484  1544 utils.py:46] yolo_darknet/conv2d_5 bn
I1029 08:49:50.583482  1544 utils.py:46] yolo_darknet/conv2d_6 bn
I1029 08:49:50.584479  1544 utils.py:46] yolo_darknet/conv2d_7 bn
I1029 08:49:50.585477  1544 utils.py:46] yolo_darknet/conv2d_8 bn
I1029 08:49:50.587471  1544 utils.py:46] yolo_darknet/conv2d_9 bn
I1029 08:49:50.589466  1544 utils.py:46] yolo_darknet/conv2d_10 bn
I1029 08:49:50.592458  1544 utils.py:46] yolo_darknet/conv2d_11 bn
I1029 08:49:50.595450  1544 utils.py:46] yolo_darknet/conv2d_12 bn
I1029 08:49:50.596447  1544 utils.py:46] yolo_darknet/conv2d_13 bn
I1029 08:49:50.598442  1544 utils.py:46] yolo_darknet/conv2d_14 bn
I1029 08:49:50.599439  1544 utils.py:46] yolo_darknet/conv2d_15 bn
I1029 08:49:50.602431  1544 utils.py:46] yolo_darknet/conv2d_16 bn
I1029 08:49:50.603429  1544 utils.py:46] yolo_darknet/conv2d_17 bn
I1029 08:49:50.605423  1544 utils.py:46] yolo_darknet/conv2d_18 bn
I1029 08:49:50.607418  1544 utils.py:46] yolo_darknet/conv2d_19 bn
I1029 08:49:50.610410  1544 utils.py:46] yolo_darknet/conv2d_20 bn
I1029 08:49:50.611407  1544 utils.py:46] yolo_darknet/conv2d_21 bn
I1029 08:49:50.613402  1544 utils.py:46] yolo_darknet/conv2d_22 bn
I1029 08:49:50.614399  1544 utils.py:46] yolo_darknet/conv2d_23 bn
I1029 08:49:50.616394  1544 utils.py:46] yolo_darknet/conv2d_24 bn
I1029 08:49:50.617391  1544 utils.py:46] yolo_darknet/conv2d_25 bn
I1029 08:49:50.620383  1544 utils.py:46] yolo_darknet/conv2d_26 bn
I1029 08:49:50.627365  1544 utils.py:46] yolo_darknet/conv2d_27 bn
I1029 08:49:50.629359  1544 utils.py:46] yolo_darknet/conv2d_28 bn
I1029 08:49:50.635343  1544 utils.py:46] yolo_darknet/conv2d_29 bn
I1029 08:49:50.637338  1544 utils.py:46] yolo_darknet/conv2d_30 bn
I1029 08:49:50.643322  1544 utils.py:46] yolo_darknet/conv2d_31 bn
I1029 08:49:50.645316  1544 utils.py:46] yolo_darknet/conv2d_32 bn
I1029 08:49:50.661274  1544 utils.py:46] yolo_darknet/conv2d_33 bn
I1029 08:49:50.663268  1544 utils.py:46] yolo_darknet/conv2d_34 bn
I1029 08:49:50.672244  1544 utils.py:46] yolo_darknet/conv2d_35 bn
I1029 08:49:50.674239  1544 utils.py:46] yolo_darknet/conv2d_36 bn
I1029 08:49:50.681220  1544 utils.py:46] yolo_darknet/conv2d_37 bn
I1029 08:49:50.683215  1544 utils.py:46] yolo_darknet/conv2d_38 bn
I1029 08:49:50.688202  1544 utils.py:46] yolo_darknet/conv2d_39 bn
I1029 08:49:50.690196  1544 utils.py:46] yolo_darknet/conv2d_40 bn
I1029 08:49:50.697178  1544 utils.py:46] yolo_darknet/conv2d_41 bn
I1029 08:49:50.699172  1544 utils.py:46] yolo_darknet/conv2d_42 bn
I1029 08:49:50.704159  1544 utils.py:46] yolo_darknet/conv2d_43 bn
I1029 08:49:50.742058  1544 utils.py:46] yolo_darknet/conv2d_44 bn
I1029 08:49:50.748041  1544 utils.py:46] yolo_darknet/conv2d_45 bn
I1029 08:49:50.785940  1544 utils.py:46] yolo_darknet/conv2d_46 bn
I1029 08:49:50.790927  1544 utils.py:46] yolo_darknet/conv2d_47 bn
I1029 08:49:50.829823  1544 utils.py:46] yolo_darknet/conv2d_48 bn
I1029 08:49:50.834809  1544 utils.py:46] yolo_darknet/conv2d_49 bn
I1029 08:49:50.874702  1544 utils.py:46] yolo_darknet/conv2d_50 bn
I1029 08:49:50.881683  1544 utils.py:46] yolo_darknet/conv2d_51 bn
I1029 08:49:50.918585  1544 utils.py:46] yolo_conv_0/conv2d_52 bn
I1029 08:49:50.923572  1544 utils.py:46] yolo_conv_0/conv2d_53 bn
I1029 08:49:50.960473  1544 utils.py:46] yolo_conv_0/conv2d_54 bn
I1029 08:49:50.964462  1544 utils.py:46] yolo_conv_0/conv2d_55 bn
I1029 08:49:51.006350  1544 utils.py:46] yolo_conv_0/conv2d_56 bn
I1029 08:49:51.011336  1544 utils.py:46] yolo_output_0/conv2d_57 bn
I1029 08:49:51.052227  1544 utils.py:46] yolo_output_0/conv2d_58 bias
I1029 08:49:51.055219  1544 utils.py:46] yolo_conv_1/conv2d_59 bn
I1029 08:49:51.056216  1544 utils.py:46] yolo_conv_1/conv2d_60 bn
I1029 08:49:51.059208  1544 utils.py:46] yolo_conv_1/conv2d_61 bn
I1029 08:49:51.065193  1544 utils.py:46] yolo_conv_1/conv2d_62 bn
I1029 08:49:51.067188  1544 utils.py:46] yolo_conv_1/conv2d_63 bn
I1029 08:49:51.076163  1544 utils.py:46] yolo_conv_1/conv2d_64 bn
I1029 08:49:51.078158  1544 utils.py:46] yolo_output_1/conv2d_65 bn
I1029 08:49:51.086136  1544 utils.py:46] yolo_output_1/conv2d_66 bias
I1029 08:49:51.087134  1544 utils.py:46] yolo_conv_2/conv2d_67 bn
I1029 08:49:51.088131  1544 utils.py:46] yolo_conv_2/conv2d_68 bn
I1029 08:49:51.089128  1544 utils.py:46] yolo_conv_2/conv2d_69 bn
I1029 08:49:51.092120  1544 utils.py:46] yolo_conv_2/conv2d_70 bn
I1029 08:49:51.093118  1544 utils.py:46] yolo_conv_2/conv2d_71 bn
I1029 08:49:51.096110  1544 utils.py:46] yolo_conv_2/conv2d_72 bn
I1029 08:49:51.097107  1544 utils.py:46] yolo_output_2/conv2d_73 bn
I1029 08:49:51.099102  1544 utils.py:46] yolo_output_2/conv2d_74 bias
I1029 08:49:51.100099  1544 Convert.py:22] weights loaded
2020-10-29 08:49:51.106167: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-10-29 08:49:52.303893: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.
2020-10-29 08:49:52.347208: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
I1029 08:49:53.194673  1544 Convert.py:26] sanity check passed
I1029 08:49:53.748191  1544 Convert.py:29] weights saved

C:\AI4Y\Single-Multiple-Custom-Object-Detection-and-Tracking-master>object_tracker.py
2020-10-29 08:51:37.091077: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-29 08:51:39.099816: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-10-29 08:51:39.129315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2060 SUPER computeCapability: 7.5
coreClock: 1.68GHz coreCount: 34 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-10-29 08:51:39.129877: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-29 08:51:39.134615: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-10-29 08:51:39.136543: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-10-29 08:51:39.137202: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-10-29 08:51:39.139865: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-10-29 08:51:39.141880: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-10-29 08:51:39.154219: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-10-29 08:51:39.154355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-10-29 08:51:39.162117: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-29 08:51:39.169240: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1f4e5df1a60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-29 08:51:39.169315: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-29 08:51:39.169671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2060 SUPER computeCapability: 7.5
coreClock: 1.68GHz coreCount: 34 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-10-29 08:51:39.169830: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-29 08:51:39.170045: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-10-29 08:51:39.170251: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-10-29 08:51:39.170480: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-10-29 08:51:39.170693: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-10-29 08:51:39.170896: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-10-29 08:51:39.171103: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-10-29 08:51:39.171339: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-10-29 08:51:39.640558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-29 08:51:39.640691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0
2020-10-29 08:51:39.640754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N
2020-10-29 08:51:39.641566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6642 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-10-29 08:51:39.643962: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1f492563eb0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-29 08:51:39.644055: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2060 SUPER, Compute Capability 7.5
2020-10-29 08:51:42.320896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2060 SUPER computeCapability: 7.5
coreClock: 1.68GHz coreCount: 34 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-10-29 08:51:42.321577: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-29 08:51:42.322166: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-10-29 08:51:42.322472: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-10-29 08:51:42.322581: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-10-29 08:51:42.322877: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-10-29 08:51:42.323091: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-10-29 08:51:42.323145: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-10-29 08:51:42.323210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-10-29 08:51:42.323446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-29 08:51:42.323633: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0
2020-10-29 08:51:42.323850: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N
2020-10-29 08:51:42.324130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6642 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "C:\AI4Y\Single-Multiple-Custom-Object-Detection-and-Tracking-master\object_tracker.py", line 31, in <module>
    encoder = gdet.create_box_encoder(model_filename, batch_size=1)
  File "C:\AI4Y\Single-Multiple-Custom-Object-Detection-and-Tracking-master\tools\generate_detections.py", line 103, in create_box_encoder
    image_encoder = ImageEncoder(model_filename, input_name, output_name)
  File "C:\AI4Y\Single-Multiple-Custom-Object-Detection-and-Tracking-master\tools\generate_detections.py", line 83, in __init__
    self.input_var = tf.get_default_graph().get_tensor_by_name(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3846, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3670, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3710, in _as_graph_element_locked
    raise KeyError("The name %s refers to a Tensor which does not "
KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."

**Comment by SaharGezer** [comment]
Got the same error

**Comment by DrPlanecraft** [comment]
Can anyone help?

**Comment by SaharGezer** [comment]
> Can anyone help?

In generate_detections.py - line 84 and 86 - change “net/%s:0” to “%s:0”

**Comment by DrPlanecraft** [comment]
right I will try

**Comment by DrPlanecraft** [comment]
BTW, by default the model is already trained to detect things right?

got another error, this time:
KeyError: "The name 'images:0' refers to a Tensor which does not exist. The operation, 'images', does not exist in the graph."

**Comment by DrPlanecraft** [comment]
The original issue has been solved

**Comment by Bhaskar476** [comment]
encoder = gdet.create_box_encoder(model_filename, batch_size=1)

KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."

I am having this error in the given line.
I am doing this code in google colab.

I have also changed the code in line 84 & 86 with "%s:0". But showing same result again.

**Comment by Bhaskar476** [comment]
> > Can anyone help?
> 
> In generate_detections.py - line 84 and 86 - change “net/%s:0” to “%s:0”

encoder = gdet.create_box_encoder(model_filename, batch_size=1)

KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."

I am having this error in the given line.
I am doing this code in google colab.

I have also changed the code in line 84 & 86 with "%s:0". But showing same result again.

**Comment by NaumanHSA** [comment]
In case if someone faces the same issue now, then you need to change "%s:0" to "net/%s:0" in both lines 84 and 86. It worked for me ;

**Comment by yanghualv7** [comment]
> In case if someone faces the same issue now, then you need to change "%s:0" to "net/%s:0" in both lines 84 and 86. It worked for me ;

Thank you very much. Your method has successfully solved my problem!
