### ISSUE TITLE
ValueError: Tensor Tensor("yolo_nms/combined_non_max_suppression/CombinedNonMaxSuppression:0", shape=(?, 100, 4), dtype=float32) is not an element of this graph.

### ISSUE THREAD

**Issue by nipun1992** [emasterclassacademy/Single-Multiple-Custom-Object-Detection-and-Tracking#19]
I am trying to perform object tracking using Deep SORT algorithm. Upon execution of the flask file in the code, it is returning the below exception :

C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\keras\engine\training_v1.py:2356: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
Traceback (most recent call last):
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\werkzeug\middleware\dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\src\app_deepsort_api.py", line 163, in PredictImage
    output = predictImage(req_data)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\src\getImagePredictionDeepSort.py", line 151, in predictImage
    boxes, scores, classes, nums = yolo.predict(img_in, steps=1)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\keras\engine\training_v1.py", line 1067, in predict
    use_multiprocessing=use_multiprocessing,
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\keras\engine\training_arrays_v1.py", line 807, in predict
    callbacks=callbacks,
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\keras\engine\training_arrays_v1.py", line 192, in model_iteration
    f = _make_execution_function(model, mode)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\keras\engine\training_arrays_v1.py", line 620, in _make_execution_function
    return model._make_execution_function(mode)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\keras\engine\training_v1.py", line 2369, in _make_execution_function
    self._make_predict_function()
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\keras\engine\training_v1.py", line 2358, in _make_predict_function
    **kwargs
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\keras\backend.py", line 4648, in function
    inputs, outputs, updates=updates, name=name, **kwargs
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\keras\backend.py", line 4419, in __init__
    with tf.control_dependencies([self.outputs[0]]):
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 5639, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 5093, in control_dependencies
    c = self.as_graph_element(c)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3998, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Users\nipun.gupta\Downloads\UniquePersonDeepSORT_1\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 4077, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("yolo_nms/combined_non_max_suppression/CombinedNonMaxSuppression:0", shape=(?, 100, 4), dtype=float32) is not an element of this graph.

Kindly requesting for suggestions on resolving this exception. Thanks

**Comment by nipun1992** [comment]
Python version is 3.7

Attaching requirements.txt file for reference to versions used for respective Python libraries

[requirements.txt](https://github.com/emasterclassacademy/Single-Multiple-Custom-Object-Detection-and-Tracking/files/9582104/requirements.txt)
